# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testCollectionView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for testCollectionView
  pod 'SDWebImage'
  target 'testCollectionViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testCollectionViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
